### ISSUE TITLE
Engines breakpoint templates must be in app/

### ISSUE THREAD

**Issue by dustinfarris** [html-next/flexi#102] opened 2016-12-23 03:08 UTC
### Summary

layouts in `/my-engine/addon/templates/**/-layouts/*` are not compiled.

### Details

ember-engines encourages you to put everything in `addon/` and doesn't even create an `app/` folder in the blueprint.  This includes templates.  ember-engines automagically re-exports everything it needs so that it is available at runtime.

Flexi compiles breakpoint templates (e.g. `-layouts/mobile.hbs`) in [`preprocessTree`](https://github.com/html-next/flexi/blob/master/index.js#L117), where it is handed all the known templates at that time.  Flexi extracts and compiles the stuff in -layouts folders, and then merges it back in with the rest.

The problem seems to be that ember-engines has not re-exported the templates yet at this stage in preprocessTree, rather it does not happen until Engines starts piecing things together in some very sophisticated treeFor* callbacks.  So, if you have a breakpoint template in `my-engine/addon/templates/index/-layouts/mobile.hbs`, it will be merged into a big 'ol app tree eventually (not sure how lazy-loading plays in here), but not in time for flexi.

https://github.com/ember-engines/ember-engines#addontemplates

**Comment by rwjblue** [comment] 2016-12-27 17:11
As far as I can tell (from the description and conversations in slack) this is actually not directly related to ember-engines at all (though it is indirectly related).  The more fundamental issue is that ember-cli currently does not call `preprocessTree` / `postprocessTree` **AT ALL** for addon's `addon/` trees. When using ember-engines, you are advised to basically "put everything" into `addon/` which is why this seems to affect ember-engines specifically.

The good news is that I submitted a PR a while back to ember-cli that fixes this exact issue, and @nathanhammond is helping to land it (fleshing out more tests in the space and whatnot).  The related PR is https://github.com/ember-cli/ember-cli/pull/6516.

**Comment by rwwagner90** [comment] 2017-01-17 20:07
It seems the PR @rwjblue mentioned has been merged. Does this fix the issue @dustinfarris?

**Comment by kybishop** [comment] 2017-02-14 02:46
@dustinfarris ^

**Comment by runspired** [comment] 2017-02-16 23:19
I believe the other thing is that you have to move the layout compiler into dependencies instead of dev-dependencies for the engines.

**Comment by rwwagner90** [comment] 2017-02-21 13:43
@dustinfarris can you try this out and do as @runspired suggested please?

**Comment by rwwagner90** [comment] 2017-04-24 13:56
Going to close this, due to lack of response from @dustinfarris. If it's still an issue, feel free to reach back out!

**Closed by rwwagner90** 2017-04-24 13:56 UTC

**Comment by bravo-kernel** [comment] 2017-05-01 15:47
Confirmed, moving flexi-layouts into `dependencies` solves everything.

No need for service injection inside the engine either, it just works as expected, picks up all the various `-layouts` directories.
