### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clientWidth' of null at monitor.js

### ISSUE THREAD

**Issue by RobIsHere** [html-next/flexi#101] opened 2016-12-21 09:15 UTC
A component in state "destroying" is added to monitoring at https://github.com/html-next/flexi/blob/master/addon/mixins/container.js#L45 

It has element = null, which leads to the issue later on. Because null.clientwidth is expected to exist here: https://github.com/html-next/flexi/blob/master/addon/lib/monitor.js#L75

![screenshot](https://cloud.githubusercontent.com/assets/13229377/21383499/5b6ee9b8-c766-11e6-8f89-731e4ea84b8b.png)

**Comment by kybishop** [comment] 2016-12-30 15:06
@RobIsHere are you saying it was it is not removed [here](https://github.com/html-next/flexi/blob/master/addon/mixins/container.js#L54) before being called in `monitor.js`?

**Comment by RobIsHere** [comment] 2016-12-30 15:36
No. This issue is not about removing.

1. A component is added while it is already in isDestroying state.

2. flexi measures and causes the error before the remove handler can do its job

3. I think the remove handler was not even called. (the component was already beyond the state that triggers this handler when it is added)

**Comment by kybishop** [comment] 2016-12-30 15:58
@RobIsHere understood. Going to think about the best way to avoid dereferencing `null` and put in a fix.

**Comment by RobIsHere** [comment] 2016-12-30 16:05
I have a small temporary fix and post it later when I'm back home. It served me quite well and maybe it's useful for you.

**Comment by kybishop** [comment] 2016-12-30 16:10
To make sure I grok the issue, it's that we call `addElementHandler` in `afterRender`, but there no element was added because the component is already in the `isDestroying` state.

If the above is true, I believe we can simply add `if (self.isDestroyed} { return; }` in the `afterRender` hook. (or maybe `isDestroying` instead of `isDestroyed`... not entirely sure what state the element is in at that point). Curious to see if this is your fix! :)

**Comment by RobIsHere** [comment] 2016-12-30 18:51
I did a specific check for this.get("isDestroying") in didInsertElement():afterRender. Maybe there were situations where the element got destroyed afterwards. I can't reproduce it anymore and don't know why I went this way exactly. Just writing this down in case something comes up.

The element === null check resolved it.

**Comment by jasonmit** [comment] 2016-12-31 00:09
I think this might be able to be fixed by canceling the timer that `run.schedule` produces in willDestroyElement.

Can someone running into the above issue verify this?

```js
  // container.js

  didInsertElement() {
    this._super();
    this._elementResize = this.elementResize.bind(this);

    this._afterRenderTimer = run.schedule('afterRender', () => {
      this.set('inserted', true);
      this.get('deviceLayout')
        .monitor
        .addElementHandler(this.element, this._elementResize);
    });
  },

  willDestroyElement() {
    this._super();

    run.cancel(this._afterRenderTimer);
    this.set('inserted', false);
    this.get('deviceLayout')
      .monitor
      .removeElementHandler(this.element, this._elementResize);
    this._elementResize = null;
  }
```

**Comment by RobIsHere** [comment] 2016-12-31 00:17
No, the fix above does not work.

**Comment by RobIsHere** [comment] 2016-12-31 00:22
It does not work because afterRender skips willDestroyElement. You could try to also cancel afterRender - don't know if you can stop a run loop entry?

The execution put in time order happens actually like this:

`
  didInsertElement() {
    this._super();
    this._elementResize = this.elementResize.bind(this);
    this._afterRenderTimer = run.schedule('afterRender', );
  },


  willDestroyElement() {
    this._super();
    run.cancel(this._afterRenderTimer);
    this.set('inserted', false);
    this.get('deviceLayout')
      .monitor
      .removeElementHandler(this.element, this._elementResize);
    this._elementResize = null;
  }


() => {
      this.set('inserted', true);
      this.get('deviceLayout')
        .monitor
        .addElementHandler(this.element, this._elementResize);
    }

`

**Comment by jasonmit** [comment] 2016-12-31 03:53
Can you throw together an example or show the steps to reproduce?

**Comment by kybishop** [comment] 2016-12-31 03:55
@jasonmit did you see a fix is already in review? https://github.com/html-next/flexi/issues/105

**Comment by kybishop** [comment] 2016-12-31 04:12
On a closer look, @jasonmit's fix _should_ work http://emberjs.com/api/classes/Ember.run.html#method_cancel

I also think this is the more correct approach since we avoid doing unnecessary work. @RobIsHere are you sure the fix doesn't work?

**Comment by jasonmit** [comment] 2016-12-31 04:52
@kybishop I saw the PR but I feel we should be canceling the timer and the fact that this isn't the case (based on what @RobIsHere said) I'd like to spend some time figuring out why that is once I figure out how to reproduce this.

**Comment by RobIsHere** [comment] 2016-12-31 08:15
It does not work. Because removing the timer isn't the point here!

The execution order is the key to understanding the issue. See the post above! I put your fix @jsonmit in the order in which the browser executes it.

The insertion of the component is happening AFTER willDestroyElement.

It is happening because of:
Ember.run.schedule('afterRender', inserterFn)

Which delays inserterFn to 'afterRender'!

But the willDestroyElement is called BEFORE even rendering, because it is already destroying on insertion.

**Comment by RobIsHere** [comment] 2016-12-31 08:24
I think cleaning up is a good idea and the right approach. Just the cleanup fix needs one more statement added. To cleanup the method that is scheduled on the ember run loop. (!that is not the timer fn!). If that's possible.

**Comment by RobIsHere** [comment] 2016-12-31 08:35
Sorry, forget the last two posts. I noticed you are actually doing the removal.

I'm surprised that it doesn't work then.

I debug it on my system. Because I have no idea how to get that into a minimal reproduction.

**Comment by kybishop** [comment] 2016-12-31 10:04
Ok here's my understanding of what's happening:

The component is rendered, triggering its `didInsertElement` hook. Here we schedule our resize handler in the 'afterRender' step of the run loop. Now the fun part: the 'afterRender' step of the run loop comes BEFORE the 'destroy' step, so we never remove our resize handler. https://guides.emberjs.com/v2.10.0/applications/run-loop/

@RobIsHere could you try the following and let me know what you get in the console... and if it magically fixes the bug? There is another bug uncovered by this one; we're accessing `this.element` directly instead of with a getter. If this doesn't work, I have a theory on how we're winding up with a null element by the time we hit `afterRender`.

```javascript
didInsertElement() {
    this._super();
    this._elementResize = this.elementResize.bind(this);
    console.log(this.get('element');
    this._afterRenderTimer = run.schedule('afterRender', () => {
      this.set('inserted', true);
      this.get('deviceLayout')
        .monitor
        .addElementHandler(this.get('element'), this._elementResize);
    });
  },
```

**Comment by kybishop** [comment] 2017-01-02 04:36
Working example with a generic component: https://ember-twiddle.com/3ca76407c810fb0c6b066c638cc2e1e8?openFiles=components.destroyed-component.js%2Ctemplates.components.service-mutating-component.hbs

In Ember <= 2.9, the afterRender occurs in the next run loop, while in Ember 2.10, it occurs in the current run loop. I'll edit this comment with a link after filing a bug in with Ember.

Either way, scheduling the destruction of the afterRender handler in willDestroyElement works in the twiddle. In the case of Ember 2.9 or less, the handler is canceled in willDestroyElement, while in Ember 2.10 the afterRender runs and the element still exists at the time.

Will update my PR with this behavior. @RobIsHere

**Comment by RobIsHere** [comment] 2017-01-02 17:36
It's really weired. Cancelling does not work. I copied @jasonmit 's code. And added some logging, so you can see the didInsert/willDestroy/afterRendering order. And the error below.

As you see in the posts above, initially I thought it was simply not cancelled at all. But @jasonmit did that and it was just not working as expected.

![screenshot](https://cloud.githubusercontent.com/assets/13229377/21593663/e11f8754-d119-11e6-81b2-193973fc8785.PNG)

**Comment by kybishop** [comment] 2017-01-02 17:47
@RobIsHere if you don't mind, could you try [with setters and getters](https://github.com/html-next/flexi/pull/105/files#diff-c61247c04c5dbc3980dadc4e59249f89R51
) instead of direct JS properties? I suspect something weird is happening to the handler. If it still doesn't work, you can log the handler in both didInsertElement and willDestroyElement to compare them.

Also, what version of Ember are you running?

**Comment by RobIsHere** [comment] 2017-01-02 17:49
Ember 2.5.1
Ember Data 2.10.0
jQuery 2.2.4

We stuck because of this Bug: https://github.com/emberjs/ember.js/issues/14539. It would affect about 5% of our users. So we skip the broken LTS Version and wait for the next one.

My workaround works for us and if you say that your solution is the way to go for the future, that's ok for me.

**Comment by RobIsHere** [comment] 2017-01-02 17:59
Found the bug. The "return" statement is missing in this method:

![screenshot](https://cloud.githubusercontent.com/assets/13229377/21593966/86ac371e-d11d-11e6-9b11-a3e46bd25af6.PNG)

**Comment by kybishop** [comment] 2017-01-02 18:01
Hah! I just found that myself. I'll dig deeper tomorrow, very late here in Thailand. Luckily I can finally reproduce the bug in my twiddle by reverting to your ember version!

**Comment by RobIsHere** [comment] 2017-01-02 18:06
The docs above state: @return {void}
So maybe they don't call it a bug but rather a memory saving feature :)

If you want to be backwards compatible, maybe cancel the timer as it's working in newer versions and additionally add this:

`
  // mixins/container.js

  didInsertElement() {
    this._super();
    this._elementResize = this.elementResize.bind(this);
    this._afterRenderTimer = run.schedule('afterRender', () => {

      // needed for older Ember
     if (this.get("isDestroying")) return;

      this.set('inserted', true);
      this.get('deviceLayout')
        .monitor
        .addElementHandler(this.element, this._elementResize);
    });
  },
`

**Comment by rwjblue** [comment] 2017-01-02 23:01
Ya, I fixed in in 2.8+ in https://github.com/emberjs/ember.js/pull/14550. It's unlikely to be backported further than 2.8 though.

**Comment by jasonmit** [comment] 2017-01-03 03:09
Given that, I think `scheduleOnce` can be safely used here instead of `schedule` which does `return` in `2.8.x`.

**Comment by kybishop** [comment] 2017-01-03 12:58
@jasonmit I did a lot of thinking on this, and think we should go with a `this.get('isDestroying')` check in the `afterRender`. This is an edge case, _and_ it only occurs in older versions of Ember. As such, we should be optimizing for the common case.

Saving and needlessly canceling a task in the common case is not ideal, whereas doing a simple boolean check (for `this.get('isDestroying')` has a minimal impact on either case. This also involves less moving parts in general; we already know `isDestroying` will be set on the component, no need for another variable in the component.

Let me know if you feel otherwise.

**Comment by rwjblue** [comment] 2017-01-03 13:46
FWIW, you can use `this.isDestroying` (no need for `this.get` as it will never be a computed property and it isn't chaining...)

**Closed** 2017-01-05 20:08 UTC
Labels: bug
